### ISSUE TITLE
Caught exception from ForgeMultipart

### ISSUE THREAD

**Issue by s0u7a** [GTNewHorizons/Hodgepodge#353] opened 2024-04-01 15:39 UTC
https://mclo.gs/C3N7660
latest forgemultipart.

**Comment by s0u7a** [comment] 2024-04-01 15:42
Does this require opening an issue in lwjgl3ify?

**Comment by eigenraven** [comment] 2024-04-01 15:49
The issue is fixed in the gtnh fork for forgemultipart https://github.com/GTNewHorizons/ForgeMultipart/.

**Closed by eigenraven** 2024-04-01 15:49 UTC

**Comment by s0u7a** [comment] 2024-04-01 15:51
thx
